version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: composepostgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/database
  server:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db 

volumes:
  postgres-db: