// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string `json:"id"`
	OnPost    bool   `json:"onPost"`
	CommentOn string `json:"commentOn"`
	Author    string `json:"author"`
	Body      string `json:"body"`
}

type CommentWithComments struct {
	Comment  *Comment               `json:"comment,omitempty"`
	Comments []*CommentWithComments `json:"comments,omitempty"`
}

type Mutation struct {
}

type NewComment struct {
	CommentOn string `json:"commentOn"`
	Author    string `json:"author"`
	Body      string `json:"body"`
}

type NewPost struct {
	Header         string `json:"header"`
	Body           string `json:"body"`
	Author         string `json:"author"`
	AllowsComments bool   `json:"allowsComments"`
}

type Post struct {
	ID             string `json:"id"`
	Author         string `json:"author"`
	Header         string `json:"header"`
	Body           string `json:"body"`
	AllowsComments bool   `json:"allowsComments"`
}

type PostWithComments struct {
	Post     *Post                  `json:"post,omitempty"`
	Comments []*CommentWithComments `json:"comments,omitempty"`
}

type Query struct {
}
